# Use the official Nginx image from Docker Hub
FROM nginx:1.25-alpine

# Copy ALL files from the current directory into the Nginx public HTML folder
COPY . /usr/share/nginx/html

# Expose port 80
EXPOSE 80